/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppMembersRouteImport } from './routes/app.members'
import { Route as AppProjectsIdRouteImport } from './routes/app.projects.$id'
import { Route as AppProjectsIdIndexRouteImport } from './routes/app.projects.$id.index'
import { Route as AppProjectsIdSettingsRouteImport } from './routes/app.projects.$id.settings'
import { Route as AppProjectsIdListRouteImport } from './routes/app.projects.$id.list'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsIdIndexRoute = AppProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdSettingsRoute = AppProjectsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppProjectsIdRoute,
} as any)
const AppProjectsIdListRoute = AppProjectsIdListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AppProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/members': typeof AppMembersRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/app/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/app/projects/$id/list': typeof AppProjectsIdListRoute
  '/app/projects/$id/settings': typeof AppProjectsIdSettingsRoute
  '/app/projects/$id/': typeof AppProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/members': typeof AppMembersRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/app/projects/$id/list': typeof AppProjectsIdListRoute
  '/app/projects/$id/settings': typeof AppProjectsIdSettingsRoute
  '/app/projects/$id': typeof AppProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/members': typeof AppMembersRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/app/projects/$id': typeof AppProjectsIdRouteWithChildren
  '/app/projects/$id/list': typeof AppProjectsIdListRoute
  '/app/projects/$id/settings': typeof AppProjectsIdSettingsRoute
  '/app/projects/$id/': typeof AppProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/members'
    | '/app/projects'
    | '/invite/$token'
    | '/app/projects/$id'
    | '/app/projects/$id/list'
    | '/app/projects/$id/settings'
    | '/app/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/members'
    | '/app/projects'
    | '/invite/$token'
    | '/app/projects/$id/list'
    | '/app/projects/$id/settings'
    | '/app/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/members'
    | '/app/projects'
    | '/invite/$token'
    | '/app/projects/$id'
    | '/app/projects/$id/list'
    | '/app/projects/$id/settings'
    | '/app/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/members': {
      id: '/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$id': {
      id: '/app/projects/$id'
      path: '/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/projects/$id/': {
      id: '/app/projects/$id/'
      path: '/'
      fullPath: '/app/projects/$id/'
      preLoaderRoute: typeof AppProjectsIdIndexRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/app/projects/$id/settings': {
      id: '/app/projects/$id/settings'
      path: '/settings'
      fullPath: '/app/projects/$id/settings'
      preLoaderRoute: typeof AppProjectsIdSettingsRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
    '/app/projects/$id/list': {
      id: '/app/projects/$id/list'
      path: '/list'
      fullPath: '/app/projects/$id/list'
      preLoaderRoute: typeof AppProjectsIdListRouteImport
      parentRoute: typeof AppProjectsIdRoute
    }
  }
}

interface AppProjectsIdRouteChildren {
  AppProjectsIdListRoute: typeof AppProjectsIdListRoute
  AppProjectsIdSettingsRoute: typeof AppProjectsIdSettingsRoute
  AppProjectsIdIndexRoute: typeof AppProjectsIdIndexRoute
}

const AppProjectsIdRouteChildren: AppProjectsIdRouteChildren = {
  AppProjectsIdListRoute: AppProjectsIdListRoute,
  AppProjectsIdSettingsRoute: AppProjectsIdSettingsRoute,
  AppProjectsIdIndexRoute: AppProjectsIdIndexRoute,
}

const AppProjectsIdRouteWithChildren = AppProjectsIdRoute._addFileChildren(
  AppProjectsIdRouteChildren,
)

interface AppProjectsRouteChildren {
  AppProjectsIdRoute: typeof AppProjectsIdRouteWithChildren
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsIdRoute: AppProjectsIdRouteWithChildren,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppMembersRoute: typeof AppMembersRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppMembersRoute: AppMembersRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
