/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppMembersRouteImport } from './routes/app.members'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as WorkspaceInviteTokenRouteImport } from './routes/workspace-invite.$token'
import { Route as AppMembersInviteRouteImport } from './routes/app.members.invite'
import { Route as AppProjectsIndexRouteImport } from './routes/app.projects.index'
import { Route as AppProjectsNewRouteImport } from './routes/app.projects.new'
import { Route as InviteTokenIndexRouteImport } from './routes/invite.$token/index'
import { Route as AppProjectsIdIndexRouteImport } from './routes/app.projects.$id.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const WorkspaceInviteTokenRoute = WorkspaceInviteTokenRouteImport.update({
  id: '/workspace-invite/$token',
  path: '/workspace-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMembersInviteRoute = AppMembersInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AppMembersRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenIndexRoute = InviteTokenIndexRouteImport.update({
  id: '/invite/$token/',
  path: '/invite/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsIdIndexRoute = AppProjectsIdIndexRouteImport.update({
  id: '/projects/$id/',
  path: '/projects/$id/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/members': typeof AppMembersRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/workspace-invite/$token': typeof WorkspaceInviteTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/members/invite': typeof AppMembersInviteRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/invite/$token/': typeof InviteTokenIndexRoute
  '/app/projects/$id/': typeof AppProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/members': typeof AppMembersRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/workspace-invite/$token': typeof WorkspaceInviteTokenRoute
  '/app': typeof AppIndexRoute
  '/app/members/invite': typeof AppMembersInviteRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/invite/$token': typeof InviteTokenIndexRoute
  '/app/projects/$id': typeof AppProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/members': typeof AppMembersRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/workspace-invite/$token': typeof WorkspaceInviteTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/members/invite': typeof AppMembersInviteRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/invite/$token/': typeof InviteTokenIndexRoute
  '/app/projects/$id/': typeof AppProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/members'
    | '/app/settings'
    | '/workspace-invite/$token'
    | '/app/'
    | '/app/members/invite'
    | '/app/projects/new'
    | '/app/projects/'
    | '/invite/$token/'
    | '/app/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/members'
    | '/app/settings'
    | '/workspace-invite/$token'
    | '/app'
    | '/app/members/invite'
    | '/app/projects/new'
    | '/app/projects'
    | '/invite/$token'
    | '/app/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/members'
    | '/app/settings'
    | '/workspace-invite/$token'
    | '/app/'
    | '/app/members/invite'
    | '/app/projects/new'
    | '/app/projects/'
    | '/invite/$token/'
    | '/app/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WorkspaceInviteTokenRoute: typeof WorkspaceInviteTokenRoute
  InviteTokenIndexRoute: typeof InviteTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/members': {
      id: '/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/workspace-invite/$token': {
      id: '/workspace-invite/$token'
      path: '/workspace-invite/$token'
      fullPath: '/workspace-invite/$token'
      preLoaderRoute: typeof WorkspaceInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/members/invite': {
      id: '/app/members/invite'
      path: '/invite'
      fullPath: '/app/members/invite'
      preLoaderRoute: typeof AppMembersInviteRouteImport
      parentRoute: typeof AppMembersRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/new': {
      id: '/app/projects/new'
      path: '/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token/': {
      id: '/invite/$token/'
      path: '/invite/$token'
      fullPath: '/invite/$token/'
      preLoaderRoute: typeof InviteTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/$id/': {
      id: '/app/projects/$id/'
      path: '/projects/$id'
      fullPath: '/app/projects/$id/'
      preLoaderRoute: typeof AppProjectsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppMembersRouteChildren {
  AppMembersInviteRoute: typeof AppMembersInviteRoute
}

const AppMembersRouteChildren: AppMembersRouteChildren = {
  AppMembersInviteRoute: AppMembersInviteRoute,
}

const AppMembersRouteWithChildren = AppMembersRoute._addFileChildren(
  AppMembersRouteChildren,
)

interface AppRouteChildren {
  AppMembersRoute: typeof AppMembersRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsIdIndexRoute: typeof AppProjectsIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMembersRoute: AppMembersRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsIdIndexRoute: AppProjectsIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WorkspaceInviteTokenRoute: WorkspaceInviteTokenRoute,
  InviteTokenIndexRoute: InviteTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
